# config on G2-server
exp_dir: ./scratch/
experiment: esm640_zs_mixneg_proteingym
# experiment: debug_dms
mode: inference
device: cuda:0
batch_size: 16
pheno_batch_size: 16
# model_path: ./scratch/dis_desc_w005/2024-04-01-10-24-47/checkpoints/bestmodel-ep38.pt
# model_path: ./scratch/dis_desc_w005/2024-04-01-10-24-47/checkpoints/best_pheno_model.pt
# model_path: ./scratch/dis_esm1280_fr1_hard100_holdout/2024-12-09-12-28-03/checkpoints/best_patho_model.pt
# model_path: ./scratch/dis_saprot_fr_hard100_rev/2025-01-06-16-04-59/checkpoints/best_patho_model.pt
# model_path: ./scratch/dis_saprotAF_fr_hard100_tr/2025-01-15-17-48-11/checkpoints/best_patho_model.pt
# model_path: ./scratch/pr_dis_saprotaf_hard100/2025-01-17-15-29-56/checkpoints/best_patho_model.pt
# model_path: ./scratch//pr_mix_saprotaf_hard100/2025-01-21-16-01-08/checkpoints/best_patho_model.pt
# model_path: ./scratch/dis_saprot_fr1_hard100_rev/2025-01-07-16-54-59/checkpoints/best_patho_model.pt
# model_path: ./scratch/dis_esm640_fr1_hard100_rev/2025-01-06-16-26-19/checkpoints/best_patho_model.pt
# model_path: ./scratch/pr_mix_ep2_esm640_ft_hard100/2025-01-29-12-59-39/checkpoints/best_patho_model.pt
# model_path: ./scratch//pr_mix_ep1_esm640_ft_mixneg200/2025-01-31-12-53-55/checkpoints/best_patho_model.pt
# model_path: ./scratch//pr_mix_esm1280_ep1_ft_mixneg200/2025-02-03-11-53-37/checkpoints/best_patho_model.pt
model_path: ./scratch/esm640_zs_randneg100_sample/2025-03-13-15-06-44/checkpoints/best_patho_model.pt
# model_path: ./scratch//esm1280_zs_randneg100_sample/2025-03-13-15-50-44/checkpoints/best_patho_model.pt
# output_file: ./dms_ontoprot_wt_score.csv
init_lr: 0.001

model:
  type: esm
  # protein_lm_path: /local/storage/yl986/script_hub/KeAP/pretrained  # KeAP model
  # protein_lm_path: zjunlp/OntoProtein
  # protein_lm_path: facebook/esm2_t12_35M_UR50D  # ESM2 480
  protein_lm_path: facebook/esm2_t30_150M_UR50D  # ESM2 640
  # protein_lm_path: facebook/esm2_t33_650M_UR50D  # ESM2 1280
  # protein_lm_path: westlake-repl/SaProt_650M_PDB  # SaProt 1280 PDB
  # protein_lm_path: westlake-repl/SaProt_650M_AF2  # SaProt 1280 AF
  # protein_lm_path: facebook/esm1b_t33_650M_UR50S  # ESM-1b
  # protein_lm_path: zjunlp/OntoProtein
  text_lm_path: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext  # PubMedBERT
  # text_lm_path: microsoft/BiomedNLP-KRISSBERT-PubMed-UMLS-EL  # KrissBERT
  # text_lm_path: michiyasunaga/BioLinkBERT-base  # BioLinkBERT-base
  frozen_bert: True
  calibration_fn_name: none
  dist_fn_name: cosine_sigmoid
  margin: 0.25  # margin for contrast loss
  adjust_logits: False

dataset:
  task_name: var_pred
  data_dir: /home/yl986/data/variant_data/pred/
  seq_fasta: ["/home/yl986/data/UniProt/uniprot_sprot.fasta",
                "/home/yl986/data/UniProt/uniprot_sprot_varsplic.fasta"]
  prot_meta_data: ["/home/yl986/data/UniProt/meta/uniprot_sprot_human_meta.txt",
                   "/home/yl986/data/UniProt/meta/uniprot_trembl_human_meta.txt"]
  input_file:
    # train: inference/vars_in_training.csv  # include all variants seen in training --- to generate load variant cache only
    train: disease_clean1/all_vars_in_training.csv
    test: inference/ProteinGym_human_single.csv
    # test: inference/ProteinGym_sample.csv
        # - inference/sample.csv
  dms_reference_file: /home/yl986/scripts/ProteinGym/reference_files/DMS_substitutions_human.csv
  phenotype_vocab_file: /home/yl986/data/variant_data/pred/disease_clean1/var_dis_vocab.txt
  phenotype_desc_file: /home/yl986/data/variant_data/pred/disease_clean1/var_dis_vocab_desc.json  # phenotype name-to-description
  use_pheno_desc: True
  context_agg_option: concat
  variant_cache_file: /home/yl986/data/variant_data/prot_var_cache.json  # update if necessary (for disease inference / with different disease aggregation method)
  pid_col: UniProt
  pos_col: Protein_position
  label_col: label
  load_variant: True
  use_protein_desc: True
  max_protein_seq_length: 1024
  use_protein_desc: True
  truncate_protein: True
  use_struct_vocab: False  # enable structure-aware sequence
  overwrite_struct_seq: True  # rerun foldseek to generate structural seq
  foldseek_bin: '/home/yl986/scripts/SaProt/bin/foldseek'
  struct_folder: '/home/yl986/data/variant_data/ProteinGym/ProteinGym_AF2_structures'
  struct_seq_file: '/home/yl986/data/variant_data/pred/prot_combine_seq.json'  # pre-processed structure-aware sequence (SaProt)
  binary_inference_only: True
  use_alphamissense: False
  alphamissense_score_dir: '/home/yl986/data/variant_data/AlphaMissense/substitutions_by_prot'

